#!/usr/bin/env python3
import argparse
import json
from pathlib import Path


def tail_lines(text, line_count):
    if not text:
        return ""
    lines = text.rstrip().splitlines()
    return "\n".join(lines[-line_count:])


def main():
    parser = argparse.ArgumentParser(
        description="Print failure details from a practice matrix JSON report."
    )
    parser.add_argument("report", help="Path to the JSON report generated by run_practice_matrix.py")
    parser.add_argument(
        "--lines",
        type=int,
        default=60,
        help="Number of stdout/stderr tail lines to show per failed script.",
    )
    args = parser.parse_args()

    payload = json.loads(Path(args.report).read_text())
    results = payload.get("results", [])
    failed = [result for result in results if result.get("status") != "ok"]

    if not failed:
        print("No failed scripts in report.")
        return 0

    for result in failed:
        print(f"[{result['status']}] {result['name']} -> {result['path']}")
        print(f"returncode: {result['returncode']}")
        stdout_tail = tail_lines(result.get("stdout_tail", ""), args.lines)
        stderr_tail = tail_lines(result.get("stderr_tail", ""), args.lines)
        if stdout_tail:
            print("--- stdout tail ---")
            print(stdout_tail)
        if stderr_tail:
            print("--- stderr tail ---")
            print(stderr_tail)
        print()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
